---

services:
  app:
    image: ghcr.io/hargata/lubelogger_mcp:latest
    # environment:
    #  - LUBELOG_INSTANCE=
    #  - LUBELOG_USER=
    #  - LUBELOG_PASS=
    restart: unless-stopped
    # expose port and/or use serving via traefik
    ports:
      - 40150:8080